version: "3"
services:
    nginx:
        build:
            context: ./
            dockerfile: nginx.Dockerfile
        volumes:
            - ./conf.d:/etc/nginx/conf.d
            - /e/series e filmes:/var/www
        networks:
            - default
        ports:
            - "${NGINX_PORT}:80"