version: "3"
services:
    nginx:
        build:
            context: ./
            dockerfile: nginx.Dockerfile
        volumes:
            - "${DIRECTORY_PATH}:/var/www"
        networks:
            - default
        ports:
            - "${NGINX_PORT}:80"